version: '3.8'

services:
  app:
    build:
      context: "."
      dockerfile: Dockerfile
      args:
        USER_ID: '${WWWUSER:-1000}'
        GROUP_ID: '${WWWGROUP:-1000}'
        USER: '${USER:-whoami}'
    restart: always
    working_dir: /var/www/
    volumes:
      - ./:/var/www

  nginx:
    image: nginx:1.19-alpine
    restart: always
    ports:
      - "8090:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d

  db:
    image: mysql:8.0
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
